on: [push, pull_request]

name: Build extension

jobs:
  build:
    name: Build and package
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Use Node.js
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install
    - name: Build venus
      run: npx grunt buildvenus
    - name: Build extension
      run: npm run compile
    - name: Package extension
      run: npm run package    
    - run: mv riscv-venus-*.vsix riscv-venus.vsix
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: riscv-venus.vsix
